name: "Setup bun environment"

runs:
  using: "composite"
  steps:
    - name: "Checkout code"
      uses: actions/checkout@v3

    - name: "Setup bun"
      uses: oven-sh/setup-bun@v1
  
    - name: "Install dependencies"
      run: bun install

    - name: "Setup environment variables"
      run: |
        cp .env.dist .env
